packages:
  - 'packages/*'
  - 'packages/**/**'
  - 'apps/*'

catalog:
  react: ^18.2.0
  react-dom: ^18.2.0

  '@types/node': ^20
  '@types/react': ^18
  '@types/react-dom': ^18

  styled-components: ^6.0.8
  '@types/styled-components': ^5.1.34

  '@vercel/kv': 3.0.0
  date-fns: ^3.2.0

  jsdom: ^25.0.1

  big.js: ^6.2.1
  '@types/big.js': ^6.2.0

  '@lingui/core': ^4.11.0
  '@lingui/react': ^4.11.0
  '@lingui/cli': ^4.11.0
  '@lingui/conf': ^4.11.0
  '@lingui/loader': ^4.11.0
  '@lingui/macro': ^4.11.0
  '@lingui/swc-plugin': 4.0.8

  '@react-aria/button': ^3.8.1
  '@react-aria/focus': ^3.14.0
  '@react-aria/interactions': ^3.21.3
  '@react-aria/utils': ^3.23.2
  '@react-stately/collections': ^3.10.0
  '@react-stately/list': ^3.9.1

  yup: ^0.32.11

  wagmi: ^2.8.1
  viem: ^2.21.35
  '@wagmi/core': ^2.11.0

  bitcoin-address-validation: ^2.2.3

  '@tanstack/react-store': ^0.5.6
  '@tanstack/react-query': ^5.35.1

  usehooks-ts: ^3.1.0

  graphql-request: ^6.1.0

  next: ^14.2.15
  '@sentry/nextjs': ^8.30.0
  negotiator: ^0.6.3
  '@types/negotiator': ^0.6.3

catalogs:
  uiPeerDeps:
    react: '>=18'
    react-dom: '>=18'
    styled-components: '>=6.0.0'
