import { bitcoinNetwork, isProd } from '@/constants';
import { queryClient } from '@/lib/react-query';
import { QueryClientProvider } from '@gobob/react-query';
import { WagmiProvider } from '@gobob/wagmi';
import { SatsWagmiConfig } from '@gobob/sats-wagmi';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import { BOBUIProvider } from '@gobob/ui';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <WagmiProvider isProd={isProd}> */}
        <QueryClientProvider client={queryClient}>
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          <SatsWagmiConfig network={bitcoinNetwork}>
            <StyledComponentsRegistry>
              <BOBUIProvider>
                {/* <ConnectProvider type='both'>
                    <CSSReset /> */}
                {children}
                {/* </ConnectProvider> */}
              </BOBUIProvider>
            </StyledComponentsRegistry>
          </SatsWagmiConfig>
        </QueryClientProvider>
        {/* </WagmiProvider> */}
      </body>
    </html>
  );
}
